
# finally & return statement BOTH will be executed in the following scenario:
    {code}
        try { throw new NotImplementedException(); }
        catch(Exception)
        {
            // ..... Handle exception
            return false;
        }
        finally { //Release shared resources }
    {code}

# The above scenario is applicable even if 'try' contained a 'return' statement. In that case too, first the
    finally would have been executed than the return statement
